### ISSUE TITLE
Feature request: Featured image ID getter

### ISSUE THREAD

**Issue by VesterDe** [anthonybudd/WP_Model#11]
It would be awesome if models could return their featured image ID, besides their URL. URL is ok, but I often need the ID of the image to work with it further.

**Comment by juslintek** [comment]
Why not write a method for it in a post model and add that method to fetch featured image ID? This abstract class of WP_Model is just a wrapper around default wordpress functions. Its not like https://github.com/rjjakes/wordpress-orm, that is an alternative to wpdb and WP_Post class at all. I'm against that feature, because its not nescessary. Basically I'm against this WP_Model class, because its a masquerade, not a tuning.

**Comment by VesterDe** [comment]
Fair point. I suppose not every class even has a featured image id.

I've given up on this repo getting updates anyway.
